#!/bin/sh
chmod 755 /usr/lib/phpserenamer/data/nautilus-scripts/phpserenamer
list=`echo /home/*`
for file in $list
do
  if -d $file/.gnome2/nautilus-scripts/; then
    ln -s -f /usr/lib/phpserenamer/data/nautilus-scripts/phpserenamer $file/.gnome2/nautilus-scripts/phpserenamer
  fi
done